site_name: markn/writing

nav:
  - The Better Angels of our Data: crowdsourcing.md
  - Cycling - The North Coast 500: nc_500.md
  - Including Javascript in Python Packages: packaging_uis_in_python.md
  - A Numerically Fused Beheading: numeric_annotation.md
  - The Snake Oil of Syntax in Applied NLP: syntax.md
  - SpaCy's Dependency Matcher - An Introduction: dependency_matcher.md
  - Cycling - Eugene, OR to San Fransisco: eugene_to_sf.md
  - Today I Learned:
    - Building Lightweight Python Docker Images: ./til/docker-python.md
    - Cloud Run triggers from GCS: ./til/cloud-run-triggers.md
  - Paper Reviews:
    - Barlow Twins: ./paper_reviews/barlow_twins.md
    - ELECTRA: ./paper_reviews/electra.md
    - No Explainability without Accountability: ./paper_reviews/interactivity_explainability.md

theme:
  name: material
  favicon: img/favicon.png
  logo: img/favicon.png
  palette:
    primary: white
    accent: blue
  highlightjs: true
  hljs_languages:
  - python
  - typescript
  - json

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

markdown_extensions:
  - toc:
        permalink: '#'
  - markdown.extensions.codehilite:
        guess_lang: true
  - admonition
  - codehilite
  - extra
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
