site_name: markn/writing

nav:
  - SpaCy's Dependency Matcher - An Introduction: dependency_matcher.md
  - Cycling - Eugene, OR to San Fransisco: eugene_to_sf.md

theme:
  name: material
  favicon: img/favicon.png
  logo: img/favicon.png
  palette:
    primary: white
    accent: blue
  highlightjs: true
  hljs_languages:
  - python
  - typescript
  - json

markdown_extensions:
  - toc:
        permalink: '#'
  - markdown.extensions.codehilite:
        guess_lang: true
  - admonition
  - codehilite
  - extra
