site_name: markn/writing

nav:
  - SpaCy's Dependency Matcher - An Introduction: dependency_matcher.md
  - Cycling - Eugene, OR to San Fransisco: eugene_to_sf.md
  - Paper Reviews:
    - ELECTRA: ./paper_reviews/electra.md

theme:
  name: material
  favicon: img/favicon.png
  logo: img/favicon.png
  palette:
    primary: white
    accent: blue
  highlightjs: true
  hljs_languages:
  - python
  - typescript
  - json

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

markdown_extensions:
  - toc:
        permalink: '#'
  - markdown.extensions.codehilite:
        guess_lang: true
  - admonition
  - codehilite
  - extra
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg