site_name: Mark Neumann's Blog

nav:
  - About Me: AboutMe.md

  - Other:
    - Cycling - Eugene, OR to San Fransisco: other/eugene_to_sf.md

theme:
  name: material
  favicon: img/favicon.png
  logo: img/favicon.png
  palette:
    primary: white
    accent: blue
  highlightjs: true
  hljs_languages:
  - python
  - typescript
  - json


markdown_extensions:
  - toc:
        permalink: '#'
  - markdown.extensions.codehilite:
        guess_lang: true
  - admonition
  - codehilite
  - extra
